[book]
authors = ["Joeyh021"]
language = "en"
multilingual = false
src = "src"
title = "Computer Systems Engineering Notes"

[output.katex]

[preprocessor.katex]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Joeyh021/notes"
edit-url-template = "https://github.com/Joeyh021/notes/edit/master/{path}"
site-url = "/notes/"

[output.html.fold]
enable = true
